### PR TITLE
upgraded projects to VS2015. allowed VSIX to install on VS2015.

### PR DESCRIPTION
**Pull request by coxymla**
#14

### CODE REVIEW

**Comment by aamarber** [comment]
Hi coxymla,

There's a way to build the plugin and install it? I need to migrate 129 projects of .NET 4 to 4.5 and I don't want to spend and hour clicking on properties :(

Thanks!

**Comment by coxymla** [comment]
Hi aamarber,

If you clone my repo it should build fine, then you can install it onto Visual Studio 2015.
All I changed was the allowable install version mask.

**Comment by aamarber** [comment]
After asking I did just that and worked, thanks a lot!

**Comment by vansickle** [comment]
Thanks, I'll try to test, merge and deploy to visual studio gallery as soon as possible.

**Pull request merged**
