### PR TITLE
Added .net 4.7 Support

### PR DESCRIPTION
**Pull request by jonny64bit**
A small change to add .net 4.7 support #31 

This is built off @Profi-Concept work, thanks

### CODE REVIEW

**Comment by niemyjski** [comment]
@jonny64bit any chance you can upload the built vsix here?

**Comment by jonny64bit** [comment]
GitHub doesn't support that file type unfortunately. It builds easy enough, id just pull it down.

**Comment by hero3616** [comment]
@jonny64bit thank you for 4.7 support. It built fine for me. But how did you find Framework id 262783? Where to get Id for new framework? I get it via runtime (change one project's framework in visual studio project properties and get it's Id in debug mode)

**Comment by jonny64bit** [comment]
@hero3616 honestly i though that was just a random id. I didn't realize it had any specific meaning. So the one i used will be wrong.

**Comment by torronen** [comment]
Thanks! Works nicely, except packages.json does not get updated which did cause problems when updating packages.

packages.json:   targetFramework="net462" =>  targetFramework="net47"

**Comment by niemyjski** [comment]
Any updates?

**Comment by vansickle** [comment]
@torronen vote for #9 if you want nuget support in TargetFrameworkMigrator

**Comment by vansickle** [comment]
@jonny64bit As already mentioned here, Id is specific, so I'm sorry, but can't merge your pull request. Checked proper Id in runtime and patched VS myself.

**Comment by jonny64bit** [comment]
Don't worry i haven't had chance to come back to this, glad its sorted one way or another.

**Pull request closed without merging**
